POST http://localhost:3002/api/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhhc2hpbCIsImlkIjoiNjdhOGM4MzcxMTMzOTIzN2Y1ZDE4YWY2IiwiaWF0IjoxNzM5MTIxODg2LCJleHAiOjE3MzkxMjU0ODZ9.niJno9uwCFXr3CJfhAV4tABO2BnayQnGt9_KRbWgMEA

{
  "title": "Golf at Nanyang CC",
  "description": "Casual game of golf for beginners.",
  "dateTime": "2025-03-21T17:00:00"
}
