DELETE  http://localhost:3002/api/events/67b05b8e751ce6562fedda93
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhhc2hpbCIsImlkIjoiNjdhOGM4MzcxMTMzOTIzN2Y1ZDE4YWY2IiwiaWF0IjoxNzM5NjEwOTA3LCJleHAiOjE3Mzk2MTQ1MDd9.OBHbA_PPaQ5yowS8bv1jKTngNxLha6iIVnfpNeiQZaM